// AUTOGENERATED FILE. DO NOT MODIFY.
// Generated via `npm run gen-shmem`

// Instance: 31868818-bdbe-413c-b9cc-f21ef42da75c

export enum ShmemDataType {
    BOOL,
    UINT8_T,
    INT8_T,
    UINT16_T,
    INT16_T,
}

export default {
    ioConfig: { offset: 0, type: ShmemDataType.UINT8_T},
    status: { offset: 1, type: ShmemDataType.UINT8_T},
    heartbeat: { offset: 2, type: ShmemDataType.BOOL},
    builtinConfig: { offset: 3, type: ShmemDataType.UINT8_T},
    builtinDioValues: { offset: 4, type: ShmemDataType.BOOL, arraySize: 4},
    extIoValues: { offset: 8, type: ShmemDataType.INT16_T, arraySize: 5},
    dio8Input: { offset: 18, type: ShmemDataType.BOOL},
    dio8Value: { offset: 19, type: ShmemDataType.BOOL},
    analog: { offset: 20, type: ShmemDataType.UINT16_T, arraySize: 2},
    leftMotor: { offset: 24, type: ShmemDataType.INT16_T},
    rightMotor: { offset: 26, type: ShmemDataType.INT16_T},
    batteryMillivolts: { offset: 28, type: ShmemDataType.UINT16_T},
    resetLeftEncoder: { offset: 30, type: ShmemDataType.BOOL},
    resetRightEncoder: { offset: 31, type: ShmemDataType.BOOL},
    leftEncoder: { offset: 32, type: ShmemDataType.INT16_T},
    rightEncoder: { offset: 34, type: ShmemDataType.INT16_T},
};
