name: PlatformIO CI

on: [pull_request, push]

defaults:
  run:
    working-directory: firmware

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build
      run: pio run
    - uses: actions/upload-artifact@v2
      with:
        name: firmware.hex
        path: firmware/.pio/build/a-star32U4/firmware.hex

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Check
      run: pio check
