// AUTOGENERATED FILE. DO NOT MODIFY.
// Generated via `npm run gen-shmem`

// Instance: 31868818-bdbe-413c-b9cc-f21ef42da75c

#pragma once
#include <stdint.h>

struct Data {
  uint8_t ioConfig;
  uint8_t status;
  bool heartbeat;
  uint8_t builtinConfig;
  bool builtinDioValues[4];
  int16_t extIoValues[5];
  bool dio8Input;
  bool dio8Value;
  uint16_t analog[2];
  int16_t leftMotor;
  int16_t rightMotor;
  uint16_t batteryMillivolts;
  bool resetLeftEncoder;
  bool resetRightEncoder;
  int16_t leftEncoder;
  int16_t rightEncoder;
};
